[[releases]]
version = "0.2.0"
date = "2026-01-28"
refs = [
    "WI-2026-01-28-001",
    "WI-2026-01-28-002",
]

[[releases]]
version = "0.1.1"
date = "2026-01-23"
refs = [
    "WI-2026-01-23-001",
    "WI-2026-01-23-002",
    "WI-2026-01-23-003",
]

[[releases]]
version = "0.1.0"
date = "2026-01-19"
refs = [
    "WI-2026-01-19-001",
    "WI-2026-01-19-002",
    "WI-2026-01-19-003",
]
