[govctl]
schema = 1
id = "WI-2026-01-19-003"
title = "fix pre-publish issues"
status = "done"
created = "2026-01-19"
started = "2026-01-19"
completed = "2026-01-19"

[content]
description = """Fix pre-publish issues."""

[[content.acceptance_criteria]]
text = "Pre-publish issues fixed"
status = "done"
category = "fixed"
